# Generated by Django 4.0 on 2021-12-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_penis_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='height',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='yearly_income',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
